// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAskNJkVtd8L0qWNLboiXNapA-2-fE3LZ0',
    appId: '1:1039441091736:web:bdefd1e45267b7392044ed',
    messagingSenderId: '1039441091736',
    projectId: 'artwaves-66d77',
    authDomain: 'artwaves-66d77.firebaseapp.com',
    storageBucket: 'artwaves-66d77.appspot.com',
    measurementId: 'G-9N6ZTNCRSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuKTGbNeMC3ZodLxThh1d-FxTR5qvH-Tg',
    appId: '1:1039441091736:android:8e37cbcfae4bc25c2044ed',
    messagingSenderId: '1039441091736',
    projectId: 'artwaves-66d77',
    storageBucket: 'artwaves-66d77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjPXgs6b2x_TafbtTzyPhbYnInPQxhKq4',
    appId: '1:1039441091736:ios:33da062ec660714c2044ed',
    messagingSenderId: '1039441091736',
    projectId: 'artwaves-66d77',
    storageBucket: 'artwaves-66d77.appspot.com',
    iosBundleId: 'com.example.artwave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjPXgs6b2x_TafbtTzyPhbYnInPQxhKq4',
    appId: '1:1039441091736:ios:0833e643635819712044ed',
    messagingSenderId: '1039441091736',
    projectId: 'artwaves-66d77',
    storageBucket: 'artwaves-66d77.appspot.com',
    iosBundleId: 'com.example.artwave.RunnerTests',
  );
}
